### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jlbeard84** [Doublevil/Houhou-SRS#38]
Hello!

I see that there have not been any commits for a while and I wanted to see if there is any roadmap established for improvements or fixes to the app.

Personally, I've been thinking about starting a project like this when I stumbled across yours. Ideally I'd like to make something that is cross platform with mobile support as well, but also don't want to start on that endeavor myself if someone is already going that route.

**Comment by Doublevil** [comment]
Hello,
I don't think I'll be actively developing new features for a good while. There is no roadmap. I do want to fix the existing issues, but I'm having a tough time finding the peace of mind to do that lately.

I made this project to help people like me learn Japanese efficiently for free. I'd be glad to see another project with a similar goal come to fruition - especially one with mobile support, as I know Houhou doesn't work for a lot of people because it's Windows only.

Hope this clears things out for you. I'm closing the issue for now, but don't hesitate to follow up and reopen if you still have concerns.
