### ISSUE TITLE
"wrap up" button is not working

### ISSUE THREAD

**Issue by paulakfleck** [Doublevil/Houhou-SRS#43]
Hello! I just started using this amazing software, but for some reason, the Wrap Up button is not working. I successfully got one response right and wanted to wrap it up, but it's just loading forever.

See the screenshot.

![image](https://user-images.githubusercontent.com/5883100/225178500-e02ccb0c-0f50-4a6e-8397-77a1aa0d0ef0.png)

Could you help me fix that? Thank you in advance!

**Comment by Doublevil** [comment]
Hello,
I think it's just a confusion on what the "wrap up" button does.
What it's intended to do is to set a cutting point where your review session will be over despite some items that might be remaining in your queue. You will still have to finish up on a few items before the review session is over, by design.
